apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse-1:8123
    isDefault: true
    jsonData:
      defaultDatabase: upbit
      port: 8123
      server: clickhouse-1
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: ""
    editable: true
